version: '3.8'
services:
  backend:
    build:
      context: ./backend
    container_name: backend
    networks:
      - app-network
    ports:
      - "5000:5000"
  frontend:
    build: .
    container_name: frontend
    ports:
      - "3000:80"
    environment:
      - API_URL=http://backend:5000
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
